config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :restaurants, only: [ :index, :show, :destroy ] do
    resources :reviews, only: [ :create, :destroy ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, length: { minimum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_counter

  private

  def set_counter
    @restaurant_count = Restaurant.count
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    respond_to do |format|
      format.html
      format.json { render json: { restaurants: @restaurants } }
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant, anchor: "review-#{@review.id}")
    else
      render 'restaurants/show'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants Ajaxified</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Font awesome -->
    <script src="https://use.fontawesome.com/f01f7e3a4c.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container">
  <h1 class="text-center">Restaurants</h1>

  <div class="flex-center">
    <div>
      <% @restaurants.each do |restaurant| %>
        <p>
          <%= link_to restaurant.name, restaurant_path(restaurant) %>
          <%= link_to restaurant, method: :delete, remote: true do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </p>
      <% end %>
    </div>
  </div>

  <div class="flex-center mt-4" data-controller="counter">
    <div class="counter">
      <span data-target="counter.count"><%= @restaurant_count %></span>
    </div>
  </div>
  <div class="flex-center mt-2">
    <p>This counter was built with stimulus: every 5sec, it fetches the number of restaurants in the database et displays it.</p>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1 class="text-center"><%= @restaurant.name %></h1>
  <p class="text-center"><%= @restaurant.address %></p>
  <p class="text-bold">
    <%= pluralize @restaurant.reviews.size, "review" %>
  </p>

  <div id="reviews">
    <% if @restaurant.reviews.blank? %>
      <p class="mb-2">Be the first to leave a review for <%= @restaurant.name %></p>
    <% else %>
      <% @restaurant.reviews.each do |review| %>
        <p id="review-<%= review.id %>">
          <%= review.content %>
          <%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete, remote: true %>
        </p>
      <% end %>
    <% end %>
  </div>

  <%= simple_form_for([ @restaurant, @review ], remote: true) do |f| %>
    <%= f.input :content, as: :text %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

  <div class="mt-4">
    <%= link_to "Back to restaurants", restaurants_path %>
  </div>
</div>